swagger: "2.0"
info:
  title: Whatever
  version: 1.0.0
host: localhost:1234
schemes:
  - http
consumes:
  - application/octet-stream
produces:
  - application/octet-stream
paths:
  /foo:
    post:
      operationId: foo
      parameters:
      - name: payload
        in: body
        schema:
          type: string
          format: binary
        required: true
      responses:
        '200':
          schema:
            type: file
  /fooArray:
    post:
      operationId: fooArray
      parameters:
        - name: payload
          in: body
          schema:
            type: string
            format: binary
            x-scala-type: Array[Byte]
            x-java-type: byte[]
          required: true
      responses:
        '200':
          schema:
            type: file
            x-scala-type: Array[Byte]
            x-java-type: byte[]
  /fooChunk:
    post:
      operationId: fooChunk
      parameters:
        - name: payload
          in: body
          schema:
            type: string
            format: binary
            x-scala-type: fs2.Chunk[Byte]
            x-java-type: java.io.InputStream
          required: true
      responses:
        '200':
          schema:
            type: file
            x-scala-type: fs2.Chunk[Byte]
            x-java-type: java.io.InputStream
