openapi: 3.0.2
info:
  title: Test for "non-REST" content types
  version: 1.0.0
paths:
  /foo:
    post:
      x-jvm-package: randomContentTypes
      operationId: doFoo
      requestBody:
        required: true
        content:
          image/png:
            schema:
              type: string
              format: binary
      responses:
        200:
          content:
            application/x-pem-file:
              schema:
                type: string
  /bar:
    post:
      x-jvm-package: randomContentTypes
      operationId: doBar
      requestBody:
        required: true
        content:
          application/sdp:
            schema:
              type: string
      responses:
        200:
          content:
            image/jpeg:
              schema:
                type: string
                format: binary